### ISSUE TITLE
file watcher limit

### ISSUE THREAD

**Issue by flipchan** [XcmSend/xcmsend.github.io#13]
Common problems:

node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^

Error: ENOSPC: System limit for number of file watchers reached, watch '/tmp/togit/app-v0.0.1/src/components/Wallet/wallet-connect/src/evm/predefinedWallet/index.ts'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2264:34)

Solution:
Increase watch file limit in file "/proc/sys/fs/inotify/max_user_watches"

**Comment by flipchan** [comment]
```
Done in 11.65s.
node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^

Error: ENOSPC: System limit for number of file watchers reached, watch '/tmp/ramsey_sync/ramsey_m2/vite.config.js'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2264:34)
    at createFsWatchInstance (file:///tmp/ramsey_sync/ramsey_m2/node_modules/vite/dist/node/chunks/dep-df561101.js:52028:17)
    at setFsWatchListener (file:///tmp/ramsey_sync/ramsey_m2/node_modules/vite/dist/node/chunks/dep-df561101.js:52075:15)
    at NodeFsHandler._watchWithNodeFs (file:///tmp/ramsey_sync/ramsey_m2/node_modules/vite/dist/node/chunks/dep-df561101.js:52230:14)
    at NodeFsHandler._handleFile (file:///tmp/ramsey_sync/ramsey_m2/node_modules/vite/dist/node/chunks/dep-df561101.js:52294:23)
    at NodeFsHandler._addToNodeFs (file:///tmp/ramsey_sync/ramsey_m2/node_modules/vite/dist/node/chunks/dep-df561101.js:52536:21)
    at async file:///tmp/ramsey_sync/ramsey_m2/node_modules/vite/dist/node/chunks/dep-df561101.js:53531:21
    at async Promise.all (index 1)
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (file:///tmp/ramsey_sync/ramsey_m2/node_modules/vite/dist/node/chunks/dep-df561101.js:53727:10)
    at NodeFsHandler._addToNodeFs (file:///tmp/ramsey_sync/ramsey_m2/node_modules/vite/dist/node/chunks/dep-df561101.js:52544:18)
    at async file:///tmp/ramsey_sync/ramsey_m2/node_modules/vite/dist/node/chunks/dep-df561101.js:53531:21
    at async Promise.all (index 1) {
  errno: -28,
  syscall: 'watch',
  code: 'ENOSPC',
  path: '/tmp/ramsey_sync/ramsey_m2/vite.config.js',
  filename: '/tmp/ramsey_sync/ramsey_m2/vite.config.js'
}

Node.js v17.8.0
filip@burko:/tmp/ramsey_sync/ramsey_m2$ su
Password: 
root@burko:/tmp/ramsey_sync/ramsey_m2# w^C
(reverse-i-search)`wat': echo "9000" > /proc/sys/fs/inotify/max_user_^Ctches
root@burko:/tmp/ramsey_sync/ramsey_m2# cat /proc/sys/fs/inotify/max_user_watches 
8192
root@burko:/tmp/ramsey_sync/ramsey_m2# echo "9000"  > /proc/sys/fs/inotify/max_user_watches 
root@burko:/tmp/ramsey_sync/ramsey_m2# exit

```

**Comment by flipchan** [comment]
added to trouble shooting
